server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: boxing_app

# ==================== SENDGRID ====================
sendgrid:
  api-key: ${SENDGRID_API_KEY}

# ==================== App admin email ====================
app:
  admin:
    email: ${APP_ADMIN_EMAIL}

# ==================== LOGGING ====================
logging:
  level:
    com.gym: DEBUG
    org.springframework.web: INFO