server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: boxing_app

  mail:
    host: smtp.sendgrid.net
    port: 465
    username: apikey
    password: ${SENDGRID_API_KEY}
    protocol: smtp
    default-encoding: UTF-8

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    com.gym: DEBUG
    org.springframework.mail: DEBUG
    jakarta.mail: DEBUG
    org.springframework.web: INFO