server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-d7jphqnavr4c73chkl30-a.singapore-postgres.render.com:5432/boxing_db_bsa3
    username: root
    password: Vks933tziSADLIXEVqqlhpoZj2FElqCN
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: boxing_app

  mail:
    host: smtp.gmail.com
    port: 587
    username: rgavhale1994@gmail.com
    password: rwou jaux qtrk yxhc   # (App password)
    protocol: smtp
    default-encoding: UTF-8

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: smtp.gmail.com

# ==================== LOGGING ====================
logging:
  level:
    com.gym: DEBUG
    org.springframework.mail: DEBUG
    jakarta.mail: DEBUG
    org.springframework.web: INFO